"""add workflows

Revision ID: 0964277882b5
Revises: 9cce2388ac46
Create Date: 2026-03-08 13:46:55.635732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0964277882b5'
down_revision: Union[str, Sequence[str], None] = '9cce2388ac46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.add_column('processes', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.execute(
        "ALTER TABLE processes ALTER COLUMN status TYPE processstatus USING status::processstatus"
    )
    op.create_foreign_key(None, 'processes', 'workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processes', type_='foreignkey')
    op.alter_column('processes', 'status',
               existing_type=sa.Enum('CREATED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='processstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('processes', 'workflow_id')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
