"""add process templates

Revision ID: 6e13d6b23966
Revises: 0964277882b5
Create Date: 2026-03-08 14:01:35.589102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e13d6b23966'
down_revision: Union[str, Sequence[str], None] = '0964277882b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_templates_id'), 'process_templates', ['id'], unique=False)
    op.add_column('processes', sa.Column('template_id', sa.Integer(), nullable=True))
    op.alter_column('processes', 'status',
               existing_type=postgresql.ENUM('CREATED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='processstatus'),
               nullable=False)
    op.create_foreign_key(None, 'processes', 'process_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processes', type_='foreignkey')
    op.alter_column('processes', 'status',
               existing_type=postgresql.ENUM('CREATED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='processstatus'),
               nullable=True)
    op.drop_column('processes', 'template_id')
    op.drop_index(op.f('ix_process_templates_id'), table_name='process_templates')
    op.drop_table('process_templates')
    # ### end Alembic commands ###
