"""add description to processes

Revision ID: 9f3aa03684d8
Revises: f54639099cfe
Create Date: 2026-02-08 21:38:27.664050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3aa03684d8'
down_revision: Union[str, Sequence[str], None] = 'f54639099cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'description')
    # ### end Alembic commands ###
