"""add description and is_active to processes

Revision ID: fe5be57db3cf
Revises: 9f3aa03684d8
Create Date: 2026-02-08 23:17:58.373464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe5be57db3cf'
down_revision: Union[str, Sequence[str], None] = '9f3aa03684d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_events', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('process_events', sa.Column('old_value', sa.String(length=255), nullable=True))
    op.add_column('process_events', sa.Column('new_value', sa.String(length=255), nullable=True))
    op.add_column('process_events', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('process_events', 'action',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('PROCESS_CREATED', 'PROCESS_UPDATED', 'STATUS_CHANGED', 'FIELD_UPDATED', name='processeventtype'),
               existing_nullable=False)
    op.drop_constraint(op.f('process_events_ibfk_2'), 'process_events', type_='foreignkey')
    op.create_foreign_key(None, 'process_events', 'users', ['created_by'], ['id'])
    op.drop_column('process_events', 'user_id')
    op.add_column('processes', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('processes', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processes', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('processes', 'is_active')
    op.add_column('process_events', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'process_events', type_='foreignkey')
    op.create_foreign_key(op.f('process_events_ibfk_2'), 'process_events', 'users', ['user_id'], ['id'])
    op.alter_column('process_events', 'action',
               existing_type=sa.Enum('PROCESS_CREATED', 'PROCESS_UPDATED', 'STATUS_CHANGED', 'FIELD_UPDATED', name='processeventtype'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('process_events', 'created_by')
    op.drop_column('process_events', 'new_value')
    op.drop_column('process_events', 'old_value')
    op.drop_column('process_events', 'description')
    # ### end Alembic commands ###
